src/Microsoft.Framework.ConfigurationModel.Json/JsonConfigurationSource.cs
test/Microsoft.Framework.ConfigurationModel.FunctionalTests/ConfigurationTests.cs
test/Microsoft.Framework.ConfigurationModel.Json.Test/JsonConfigurationSourceTest.cs
test/Microsoft.Framework.ConfigurationModel.Xml.Test/XmlConfigurationSourceTest.cs

This addresses the below bugs:
https://github.com/aspnet/Configuration/issues/126
https://github.com/aspnet/Configuration/issues/106
Currently to represent a JSON element's path from the top node we use ':' as a delimiter. For example:
```
{
"one":
{
"two": "two value"
}
}
```
The convention to identify "two" here is one:two. This works fine for normal scenarios as we get the JSON node's Path which is one.two and replace the '.' => ':'.
This fails when the node name contains a '.'. For example replace the name of 'two' to 'a.b', JSON.net escapes such a node's name to ['a.b']. So our code replacing all '.' => ':' will mess up the key name.
This fix addresses the problem by replacing '.' => ':' only if it is not with in ['..'].
/CC @ChengTian @Eilon @mikary

Fixing the JSON config source to handle keys with '.'

---

src/Microsoft.Framework.ConfigurationModel.Xml/EncryptedXmlDocumentDecryptor.cs
src/Microsoft.Framework.ConfigurationModel.Xml/Properties/Resources.Designer.cs
src/Microsoft.Framework.ConfigurationModel.Xml/Resources.resx
src/Microsoft.Framework.ConfigurationModel.Xml/XmlConfigurationSource.cs
src/Microsoft.Framework.ConfigurationModel.Xml/XmlDocumentDecryptor.cs
src/Microsoft.Framework.ConfigurationModel.Xml/project.json
test/Microsoft.Framework.ConfigurationModel.Xml.Test/XmlConfigurationSourceTest.AspNet50.cs
test/Microsoft.Framework.ConfigurationModel.Xml.Test/XmlConfigurationSourceTest.AspNetCore50.cs
test/Microsoft.Framework.ConfigurationModel.Xml.Test/XmlConfigurationSourceTest.cs

Currently only desktop CLR supports this pending EncryptedXml being checked in to Core CLR.
/cc @glennc @blowdart @victorhurdugaci

Add support for encrypted XML-based config

---

src/Microsoft.Framework.ConfigurationModel.Interfaces/IConfiguration.cs
src/Microsoft.Framework.ConfigurationModel.Interfaces/IConfigurationSourceRoot.cs
src/Microsoft.Framework.ConfigurationModel.Json/JsonConfigurationExtension.cs
src/Microsoft.Framework.ConfigurationModel.Xml/XmlConfigurationExtension.cs
src/Microsoft.Framework.ConfigurationModel/Configuration.cs
src/Microsoft.Framework.ConfigurationModel/ConfigurationExtensions.cs
src/Microsoft.Framework.ConfigurationModel/ConfigurationFocus.cs
src/Microsoft.Framework.ConfigurationModel/Sources/CommandLineConfigurationSource.cs
test/Microsoft.Framework.ConfigurationModel.FunctionalTests/ConfigurationTests.cs
test/Microsoft.Framework.ConfigurationModel.Test/ConfigurationTest.cs

- IConfigurationSourceContainer renamed to IConfigurationSourceRoot
- IConfigurationSourceRoot is no longer an IEnumerable
- Added Sources property to IConfigurationSourceRoot
- Moved Reload() from IConfiguration to IConfigurationSourceRoot
- Make ConfigurationFocus internal
- Configuration class constructor accepts params IConfigurationSource[]
- CommandLineConfigurationSource accepts IEnumerable instead of string array
- CommandLineConfigurationSource's args property is protected
Fixes https://github.com/aspnet/Configuration/issues/144
Fixes https://github.com/aspnet/Configuration/issues/142
Fixes https://github.com/aspnet/Configuration/issues/141
Fixes https://github.com/aspnet/Configuration/issues/140
cc @glennc

Final API review changes

---

README.md
src/Microsoft.Framework.ConfigurationModel/ConfigurationExtensions.cs

Added extension to accept switchMappings along with command line arguments for command line configuration source.
I took some time to surprisingly observe that `switchMappings` part was implemented via `CommandLineConfigurationSource` ctor but `ConfigurationExtensions` didn't had option to feed them during `AddCommandLine`.
I even see `using System.Collections.Generic;` in `ConfigurationExtensions` which is unused. Seems like implementation is in place along with few Unit Tests which passes. But no option to use `switchMappings`.
P.S - My first PR, excited. (Already signed Contributor License Agreement)

Added extension to accept switchMappings

---

src/Microsoft.Framework.ConfigurationModel.Json/JsonConfigurationFileParser.cs
src/Microsoft.Framework.ConfigurationModel.Json/JsonConfigurationSource.cs
src/Microsoft.Framework.ConfigurationModel.Json/Properties/Resources.Designer.cs
src/Microsoft.Framework.ConfigurationModel.Json/Resources.resx
src/Microsoft.Framework.ConfigurationModel.Json/project.json
src/Microsoft.Framework.ConfigurationModel/ConfigurationKeyComparer.cs
src/Microsoft.Framework.ConfigurationModel/Properties/AssemblyInfo.cs
src/Microsoft.Framework.ConfigurationModel/Sources/ConfigurationSource.cs
test/Microsoft.Framework.ConfigurationModel.FunctionalTests/ArrayTests.cs
test/Microsoft.Framework.ConfigurationModel.FunctionalTests/ConfigurationTests.cs
test/Microsoft.Framework.ConfigurationModel.Json.Test/ArrayTest.cs
test/Microsoft.Framework.ConfigurationModel.Json.Test/JsonConfigurationSourceTest.cs
test/Microsoft.Framework.ConfigurationModel.Test.Common/ConfigurationSourceExtensions.cs
test/Microsoft.Framework.ConfigurationModel.Test.Common/TestStreamHelpers.cs
test/Microsoft.Framework.ConfigurationModel.Test/CommandLineConfigurationSourceTest.cs
test/Microsoft.Framework.ConfigurationModel.Test/ConfigurationExtensionsTest.cs
test/Microsoft.Framework.ConfigurationModel.Test/ConfigurationPathComparerTest.cs
test/Microsoft.Framework.ConfigurationModel.Test/ConfigurationTest.cs
test/Microsoft.Framework.ConfigurationModel.Test/EnvironmentVariablesConfigurationSourceTest.cs
test/Microsoft.Framework.ConfigurationModel.Test/IniFileConfigurationSourceTest.cs
test/Microsoft.Framework.ConfigurationModel.Xml.Test/XmlConfigurationExtensionTest.cs
test/Microsoft.Framework.ConfigurationModel.Xml.Test/XmlConfigurationSourceTest.AspNet50.cs
test/Microsoft.Framework.ConfigurationModel.Xml.Test/XmlConfigurationSourceTest.AspNetCore50.cs
test/Microsoft.Framework.ConfigurationModel.Xml.Test/XmlConfigurationSourceTest.cs

Fixes https://github.com/aspnet/Configuration/issues/115
- Support for JSON arrays
- Use the json.net parser instead of manually parsing the json
- Simplified some test code
cc @ChengTian @lodejard @glennc @anurse

Support for json arrays + some rewrite

---

src/Microsoft.Framework.ConfigurationModel/Configuration.cs
src/Microsoft.Framework.ConfigurationModel/Properties/AssemblyInfo.cs
test/Microsoft.Framework.ConfigurationModel.Json.Test/ArrayTest.cs
test/Microsoft.Framework.ConfigurationModel.Json.Test/JsonConfigurationSourceTest.cs
test/Microsoft.Framework.ConfigurationModel.Test/ConfigurationTest.cs

@Eilon, in response to your comment [here](https://github.com/aspnet/Configuration/pull/186):
> IVT is to be used only for the unit test assembly of this assembly. Make the type(s) in question public and move to a  .Internal  namespace.
Couldn't move to an internal namespace because it is just a method. Also, moving it to an extension method would be strange because this method needs access to private fields.

Remove IVT for some unit tests

---

src/Microsoft.Framework.Configuration.Json/JsonConfigurationSource.cs
src/Microsoft.Framework.Configuration.Xml/EncryptedXmlDocumentDecryptor.cs
src/Microsoft.Framework.Configuration.Xml/XmlConfigurationSource.cs
src/Microsoft.Framework.Configuration.Xml/XmlDocumentDecryptor.cs

I think it will be better if we update the namespace for ```JsonConfigurationSource``` to ```Microsoft.Framework.Configuration.Json``` instead of ```Microsoft.Framework.Configuration``` as also  ```Microsoft.Framework.Configuration.Xml``` instead of ```Microsoft.Framework.Configuration``` as well as other classes ```EncryptedXmlDocumentDecryptor``` and ```XmlDocumentDecryptor``` to ```Microsoft.Framework.Configuration.Xml```

Fix Namespaces

---

src/Microsoft.Framework.Configuration.Binder/ConfigurationBinder.cs
test/Microsoft.Framework.Configuration.Binder.Test/ConfigurationBinderTests.cs
test/Microsoft.Framework.Configuration.Binder.Test/ConfigurationCollectionBindingTests.cs

+ New Get and Get<T> extension methods
+ Binding scalars works with all methods now in addition to POCOs.
+ New unit tests
#281

ConfigurationBinder Bind to support scalar value, added new Get<T>

---

src/Microsoft.Framework.Configuration.CommandLine/CommandLineConfigurationExtensions.cs
src/Microsoft.Framework.Configuration.EnvironmentVariables/EnvironmentVariablesExtensions.cs
src/Microsoft.Framework.Configuration/MemoryConfigurationExtensions.cs
test/Microsoft.Framework.Configuration.Binder.Test/ConfigurationBinderTests.cs
test/Microsoft.Framework.Configuration.Binder.Test/ConfigurationCollectionBindingTests.cs
test/Microsoft.Framework.Configuration.FileExtensions.Test/FileConfigurationBuilderExtensionsTest.cs
test/Microsoft.Framework.Configuration.FunctionalTests/ArrayTests.cs
test/Microsoft.Framework.Configuration.FunctionalTests/ConfigurationTests.cs
test/Microsoft.Framework.Configuration.Ini.Test/IniConfigurationExtensionsTest.cs
test/Microsoft.Framework.Configuration.Json.Test/ArrayTest.cs
test/Microsoft.Framework.Configuration.Json.Test/JsonConfigurationExtensionsTest.cs
test/Microsoft.Framework.Configuration.Test/ConfigurationTest.cs
test/Microsoft.Framework.Configuration.Xml.Test/XmlConfigurationExtensionsTest.cs

Code cleanup: Use configurationBuilder or builder as name of parameters of type IConfigurationBuilder

---

src/Microsoft.Extensions.Configuration.FileExtensions/FileConfigurationExtensions.cs
src/Microsoft.Extensions.Configuration.FileProviderExtensions/ConfigurationRootExtensions.cs
test/Microsoft.Extensions.Configuration.FileExtensions.Test/FileConfigurationBuilderExtensionsTest.cs
test/Microsoft.Extensions.Configuration.FunctionalTests/ConfigurationTests.cs

Currently all of our samples are broken when running with dnx since configuration cannot find the `hosting.json` that is in the sample's directory. Instead, it is looking for it in the runtime directory as indicated by the appdomain. We'll revert the behaviour change for now.
cc @victorhurdugaci

Reverting behaviour change to setting configuration base path

---

test/Microsoft.Extensions.Configuration.FileExtensions.Test/FileConfigurationBuilderExtensionsTest.cs

These tests will currently break on *nix systems since they use the other slash. Copying over the slash behaviour from `PhysicalFileProvider`: https://github.com/aspnet/FileSystem/blob/dev/src/Microsoft.Extensions.FileProviders.Physical/PhysicalFileProvider.cs#L109-L118.
cc @HaoK

Fix tests on non-windows systems

---

test/Microsoft.Extensions.Configuration.FunctionalTests/ConfigurationTests.cs

cc @HaoK this seems flaky too. Fails about half the time on linux locally as well.

Diable flaky test on linux

---

.gitignore
src/Microsoft.Extensions.Configuration.UserSecrets/build/netstandard1.0/Microsoft.Extensions.Configuration.UserSecrets.targets
test/Microsoft.Extensions.Configuration.UserSecrets.Test/MsBuildTargetTest.cs

Add a warning message when users have referenced this Ms.Ex.Cfg.UserSecrets package but have not set the `<UserSecretsId>` property in their csproj.
Also, adds functional test for user secret build target. (Currently skipped until our CI picks up CLI preview3).
cc @Eilon @divega @glennc

Add warning to UserSecrets build target and fix incremental build

---

src/Microsoft.Extensions.Configuration.UserSecrets/ConfigurationExtensions.cs
src/Microsoft.Extensions.Configuration.UserSecrets/Properties/Resources.Designer.cs
src/Microsoft.Extensions.Configuration.UserSecrets/Resources.resx
test/Microsoft.Extensions.Configuration.UserSecrets.Test/ConfigurationExtensionTest.cs

Mitigates #543. A full fix requires templates to start using this overload instead of `.AddUserSecrets()`.
Also fixes the NRE for null entry assemblies to be more user-friendly.

Add AddUserSecrets<TStartup>()

---

src/Microsoft.Extensions.Configuration.AzureKeyVault/DefaultKeyVaultSecretManager.cs

DefaultKeyVaultSecretManager replaces "--" (not "__") with ":"

Correct DefaultKeyVaultSecretManager documentation

---

Configuration.sln
build/common.props
global.json
samples/KeyVaultSample/KeyVaultSample.csproj
src/Microsoft.Extensions.Configuration.Abstractions/Microsoft.Extensions.Configuration.Abstractions.csproj
src/Microsoft.Extensions.Configuration.AzureKeyVault/Microsoft.Extensions.Configuration.AzureKeyVault.csproj
src/Microsoft.Extensions.Configuration.Binder/Microsoft.Extensions.Configuration.Binder.csproj
src/Microsoft.Extensions.Configuration.CommandLine/Microsoft.Extensions.Configuration.CommandLine.csproj
src/Microsoft.Extensions.Configuration.EnvironmentVariables/Microsoft.Extensions.Configuration.EnvironmentVariables.csproj
src/Microsoft.Extensions.Configuration.FileExtensions/Microsoft.Extensions.Configuration.FileExtensions.csproj
src/Microsoft.Extensions.Configuration.Ini/Microsoft.Extensions.Configuration.Ini.csproj
src/Microsoft.Extensions.Configuration.Json/Microsoft.Extensions.Configuration.Json.csproj
src/Microsoft.Extensions.Configuration.UserSecrets/Microsoft.Extensions.Configuration.UserSecrets.csproj
src/Microsoft.Extensions.Configuration.Xml/Microsoft.Extensions.Configuration.Xml.csproj
src/Microsoft.Extensions.Configuration/Microsoft.Extensions.Configuration.csproj
test/Microsoft.Extensions.Configuration.AzureKeyVault.Test/Microsoft.Extensions.Configuration.AzureKeyVault.Test.csproj
test/Microsoft.Extensions.Configuration.Binder.Test/Microsoft.Extensions.Configuration.Binder.Test.csproj
test/Microsoft.Extensions.Configuration.CommandLine.Test/Microsoft.Extensions.Configuration.CommandLine.Test.csproj
test/Microsoft.Extensions.Configuration.EnvironmentVariables.Test/Microsoft.Extensions.Configuration.EnvironmentVariables.Test.csproj
test/Microsoft.Extensions.Configuration.FileExtensions.Test/Microsoft.Extensions.Configuration.FileExtensions.Test.csproj
test/Microsoft.Extensions.Configuration.FunctionalTests/Microsoft.Extensions.Configuration.FunctionalTests.csproj
test/Microsoft.Extensions.Configuration.Ini.Test/Microsoft.Extensions.Configuration.Ini.Test.csproj
test/Microsoft.Extensions.Configuration.Json.Test/Microsoft.Extensions.Configuration.Json.Test.csproj
test/Microsoft.Extensions.Configuration.Test.Common/Microsoft.Extensions.Configuration.Test.Common.csproj
test/Microsoft.Extensions.Configuration.Test/Microsoft.Extensions.Configuration.Test.csproj
test/Microsoft.Extensions.Configuration.UserSecrets.Test/Microsoft.Extensions.Configuration.UserSecrets.Test.csproj
test/Microsoft.Extensions.Configuration.UserSecrets.Test/MsBuildTargetTest.cs
test/Microsoft.Extensions.Configuration.Xml.Test/Microsoft.Extensions.Configuration.Xml.Test.csproj

Trims lots of fat from csproj. Removes default globs, package reference to NETStandard.Library/Microsoft.NETCore.App, and transitive references.
cc @divega

Upgrade to RC.3

---

Configuration.sln
build/dependencies.props
samples/KeyVaultSample/KeyVaultSample.csproj
src/Microsoft.Extensions.Configuration.Abstractions/Microsoft.Extensions.Configuration.Abstractions.csproj
src/Microsoft.Extensions.Configuration.AzureKeyVault/Microsoft.Extensions.Configuration.AzureKeyVault.csproj
src/Microsoft.Extensions.Configuration.DockerSecrets/Microsoft.Extensions.Configuration.DockerSecrets.csproj
src/Microsoft.Extensions.Configuration.FileExtensions/Microsoft.Extensions.Configuration.FileExtensions.csproj
src/Microsoft.Extensions.Configuration.Json/Microsoft.Extensions.Configuration.Json.csproj
test/Microsoft.Extensions.Configuration.AzureKeyVault.Test/Microsoft.Extensions.Configuration.AzureKeyVault.Test.csproj
test/Microsoft.Extensions.Configuration.Binder.Test/Microsoft.Extensions.Configuration.Binder.Test.csproj
test/Microsoft.Extensions.Configuration.CommandLine.Test/Microsoft.Extensions.Configuration.CommandLine.Test.csproj
test/Microsoft.Extensions.Configuration.DockerSecrets.Test/Microsoft.Extensions.Configuration.DockerSecrets.Test.csproj
test/Microsoft.Extensions.Configuration.EnvironmentVariables.Test/Microsoft.Extensions.Configuration.EnvironmentVariables.Test.csproj
test/Microsoft.Extensions.Configuration.FileExtensions.Test/Microsoft.Extensions.Configuration.FileExtensions.Test.csproj
test/Microsoft.Extensions.Configuration.FunctionalTests/Microsoft.Extensions.Configuration.FunctionalTests.csproj
test/Microsoft.Extensions.Configuration.Ini.Test/Microsoft.Extensions.Configuration.Ini.Test.csproj
test/Microsoft.Extensions.Configuration.Json.Test/Microsoft.Extensions.Configuration.Json.Test.csproj
test/Microsoft.Extensions.Configuration.Test.Common/Microsoft.Extensions.Configuration.Test.Common.csproj
test/Microsoft.Extensions.Configuration.Test/Microsoft.Extensions.Configuration.Test.csproj
test/Microsoft.Extensions.Configuration.UserSecrets.Test/Microsoft.Extensions.Configuration.UserSecrets.Test.csproj
test/Microsoft.Extensions.Configuration.Xml.Test/Microsoft.Extensions.Configuration.Xml.Test.csproj

Unify dependency versions via the 'dependencies.props' file.
Remove workarounds.
cc @JunTaoLuo I'm working on doing a similar change this across all Universe repos.

Cleanup MSBuild conversion

---

src/Microsoft.Extensions.Configuration.Abstractions/IConfigurationBuilder.cs
src/Microsoft.Extensions.Configuration/ConfigurationBuilder.cs

Fixes two occurrences of the word "configuation" in both the IConfigurationBuilder interface and the implementation ConfigurationBuilder class XML documentation comments.

Fix minor XML comment typos

---

src/Microsoft.Extensions.Configuration.UserSecrets/Properties/Resources.Designer.cs
src/Microsoft.Extensions.Configuration.UserSecrets/Resources.resx
src/Microsoft.Extensions.Configuration.UserSecrets/build/GenerateUserSecretsAttribute.targets

PM's don't like the UserSecrets build warning when using Microsoft.AspNetCore.All. So removing it.
Closes https://github.com/aspnet/Configuration/issues/651
Incidentally closes https://github.com/aspnet/Configuration/issues/548 and closes https://github.com/aspnet/Configuration/issues/547 which were about making improvements to the build warning.

UserSecrets: remove build warning and tweak runtime error

---

src/Microsoft.Extensions.Configuration.Json/JsonConfigurationFileParser.cs
test/Microsoft.Extensions.Configuration.Json.Test/JsonConfigurationTest.cs

Fixes https://github.com/aspnet/Configuration/issues/470.
This is technically a breaking change: previously, a float value bound to string would set it using the current culture, with this change, it would use the invariant culture. But I'd argue that:
1. Such behavior is incorrect, configuration should never use the current culture.
2. It's worth it to be able to bind a float value to float (when having non-English current culture).
cc: @HaoK, @divega

Use invariant culture in JSON parser

---

src/Microsoft.Extensions.Configuration.Binder/ConfigurationBinder.cs
test/Microsoft.Extensions.Configuration.Binder.Test/ConfigurationCollectionBindingTests.cs

Configuration dictionaries will now be able to keyed by enums
- Added enum key handling in BindDictionary method
- Added test case with enum keys

Issue #546: Add support for configurations with dictionaries keyed by enums

---

test/Microsoft.Extensions.Configuration.FunctionalTests/ConfigurationTests.cs

Ideally we wouldn't need a random wait in these tests but the `ChangeToken` is too unreliable to use because of https://github.com/aspnet/Configuration/issues/624 and you can't tell what triggered the token especially since it can be triggered by any of the configured providers.

Increase wait times for functional tests

---

samples/KeyVaultSample/EnvironmentSecretManager.cs

@pakrym
Without the handling of "--" within a secret identifier name the keys never get turned into sections separated by the ConfigurationPath.KeyDelimiter. Reference the DefaultKeyVaultSecretManager class used by default unless replaced by EnvironmentSecretManager.
I've already opened a PR on the Microsoft docs side to address this problem: 
https://github.com/aspnet/Docs/pull/3525
DefaultKeyVaultSecretManager implementation with "--" handling:
https://github.com/aspnet/Configuration/blob/dev/src/Microsoft.Extensions.Configuration.AzureKeyVault/DefaultKeyVaultSecretManager.cs

Add ConfigurationPath.KeyDelimiter replacement for "--" to GetKey

---

build/dependencies.props
samples/KeyVaultSample/KeyVaultSample.csproj

Address #640 The new stable version 2.3.1 was published today, so we can use this for our RTM release after testing. Will also update BuildTools and Identity.

Update Microsoft.Azure.KeyVault version

---

build/dependencies.props

https://github.com/aspnet/Configuration/issues/691

Update AzureKeyVaultVersion to 2.3.2

---

src/Config.AzureKeyVault/AzureKeyVaultConfigurationProvider.cs

- Add additional ConfigureAwait(false)
Addresses #737 
I've mentioned how this solves the issue with netframework471, I would love to receive some feedback on this change (even though it's really small).
I've followed the practices highlighted in [Don't Block on Async Code](https://blog.stephencleary.com/2012/07/dont-block-on-async-code.html) and [Async/Await - Best Practices in Asynchronous Programming](https://msdn.microsoft.com/en-us/magazine/jj991977.aspx).
I'd be really happy to incorporate any feedback!

Prevent Deadlock in AzureKeyVaultProvider Load

---

src/Config.CommandLine/CommandLineConfigurationProvider.cs
test/Config.CommandLine.Test/CommandLineTest.cs

Fixes https://github.com/aspnet/Configuration/issues/780
Note: some of the proposed use cases were not updated since they were currently 'valid', namely there's no validation on the values today, so these examples result in different behavior than listed in the issue:
CLI Args | Config Key/Value Pairs
---|-----
--foo /bar=baz | foo="/bar=baz"
/foo=bar --biz /baz=boo | foo=bar, biz="/baz=boo"
-f=bar --biz -b=boo | foo=bar, biz="-b=boo" (assuming mappings of foo->f & baz->b)
@ajcvickers @davidfowl @DamianEdwards @mikeharder

Make command line less strict

---

src/Config.AzureKeyVault/AzureKeyVaultConfigurationProvider.cs
test/Config.AzureKeyVault.Test/AzureKeyVaultConfigurationTest.cs

- KeyVaultClient throws when calling GetSecret on a secret ID which is disabled.
- Need to guard against this case in Provider load
- added enabled=True attributes to all current tests
- added test case to ensure secret with null attributes, or null or false disabled value is ignored
Addresses #771

Only call GetSecret on secrets which are not disabled

---

src/Config.KeyPerFile/KeyPerFileConfigurationProvider.cs

Docker secrets created on a Linux swarm using `echo "secret contents" | docker secret create test-secret -` will append a newline on the end of the secret contents. In a dotnetcore app running in a dockerized service with this secret exposed to the service, the `DockerSecretsConfigurationProvider` reads the secret with the newline character into the Configuration (resulting in something like "secret contents\n"). This is clearly not the intended secret contents.
Addresses Issue #701

Trim unintended Environment.NewLine from docker secret contents before adding to Configuration

---

Directory.Build.props
src/Config.UserSecrets/build/netstandard2.0/Microsoft.Extensions.Configuration.UserSecrets.targets
test/Config.UserSecrets.Test/Config.UserSecrets.Test.csproj
test/Config.UserSecrets.Test/MsBuildTargetTest.cs

Assembly attribute generation for F# requires using a different item group. See Microsoft/visualfsharp#5549 
Also fixes https://github.com/aspnet/Configuration/issues/740
cc @KevinRansom

Fix secret assembly attribute generation for F#
