src/Microsoft.Framework.ConfigurationModel.Json/project.json, src/Microsoft.Framework.ConfigurationModel.Shared/project.json, src/Microsoft.Framework.ConfigurationModel.Xml/project.json, src/Microsoft.Framework.ConfigurationModel/project.json, test/Microsoft.Framework.ConfigurationModel.FunctionalTests/project.json, test/Microsoft.Framework.ConfigurationModel.Json.Test/project.json, test/Microsoft.Framework.ConfigurationModel.Test/project.json, test/Microsoft.Framework.ConfigurationModel.Xml.Test/project.json
@ChengTian 
Just FYI...the Xunit packages are not available on public Nuget feed and we are figuring out if we need to create a separate feed for external packages, but other than that please take a look at the changes to other packages.
=> Changed package versions to beta2

Configuration.sln, src/Microsoft.Framework.ConfigurationModel.Json/JsonConfigurationSource.cs, src/Microsoft.Framework.ConfigurationModel.Xml/XmlConfigurationSource.cs, src/Microsoft.Framework.ConfigurationModel/ConfigurationFocus.cs, src/Microsoft.Framework.ConfigurationModel/Sources/CommandLineConfigurationSource.cs, src/Microsoft.Framework.ConfigurationModel/Sources/ConfigurationSource.cs, src/Microsoft.Framework.ConfigurationModel/Sources/EnvironmentVariablesConfigurationSource.cs, src/Microsoft.Framework.ConfigurationModel/Sources/IniFileConfigurationSource.cs, src/Microsoft.Framework.ConfigurationModel/Sources/MemoryConfigurationSource.cs, test/Microsoft.Framework.ConfigurationModel.FunctionalTests/ConfigurationTests.cs, test/Microsoft.Framework.ConfigurationModel.FunctionalTests/project.json, test/Microsoft.Framework.ConfigurationModel.Json.Test/JsonConfigurationSourceTest.cs, test/Microsoft.Framework.ConfigurationModel.Json.Test/project.json, test/Microsoft.Framework.ConfigurationModel.Test.Common/IConfigurationSourceExtensions.cs, test/Microsoft.Framework.ConfigurationModel.Test.Common/Microsoft.Framework.ConfigurationModel.Test.Common.kproj, test/Microsoft.Framework.ConfigurationModel.Test.Common/project.json, test/Microsoft.Framework.ConfigurationModel.Test/CommandLineConfigurationSourceTest.cs, test/Microsoft.Framework.ConfigurationModel.Test/ConfigurationTest.cs, test/Microsoft.Framework.ConfigurationModel.Test/EnvironmentVariablesConfigurationSourceTest.cs, test/Microsoft.Framework.ConfigurationModel.Test/IniFileConfigurationSourceTest.cs, test/Microsoft.Framework.ConfigurationModel.Test/project.json, test/Microsoft.Framework.ConfigurationModel.Xml.Test/XmlConfigurationSourceTest.cs, test/Microsoft.Framework.ConfigurationModel.Xml.Test/project.json
Fixes https://github.com/aspnet/Configuration/issues/133
Fixes https://github.com/aspnet/Configuration/issues/139
- ConfigurationFocus should take an IConfiguration argument  
- Made Data property protected
- Added set to Data property
- Removed SetData
- Updated tests to use only the new public APIs
@glennc please review
=> Api changes (part 1)

src/Microsoft.Framework.ConfigurationModel.Interfaces/IConfiguration.cs, src/Microsoft.Framework.ConfigurationModel.Interfaces/IConfigurationSourceRoot.cs, src/Microsoft.Framework.ConfigurationModel.Json/JsonConfigurationExtension.cs, src/Microsoft.Framework.ConfigurationModel.Xml/XmlConfigurationExtension.cs, src/Microsoft.Framework.ConfigurationModel/Configuration.cs, src/Microsoft.Framework.ConfigurationModel/ConfigurationExtensions.cs, src/Microsoft.Framework.ConfigurationModel/Internal/ConfigurationFocus.cs, src/Microsoft.Framework.ConfigurationModel/Sources/CommandLineConfigurationSource.cs, test/Microsoft.Framework.ConfigurationModel.FunctionalTests/ConfigurationTests.cs, test/Microsoft.Framework.ConfigurationModel.Test/ConfigurationTest.cs
Had to revert the change [here](https://github.com/aspnet/Configuration/pull/149).
Now this is the real PR. It also addresses the PR comments in the previous one.
=> API review changes

build.cmd, build.sh, src/Microsoft.Framework.ConfigurationModel.Interfaces/project.json, src/Microsoft.Framework.ConfigurationModel.Json/project.json, src/Microsoft.Framework.ConfigurationModel.Shared/PathResolver.cs, src/Microsoft.Framework.ConfigurationModel.Shared/project.json, src/Microsoft.Framework.ConfigurationModel.Xml/EncryptedXmlDocumentDecryptor.cs, src/Microsoft.Framework.ConfigurationModel.Xml/XmlDocumentDecryptor.cs, src/Microsoft.Framework.ConfigurationModel.Xml/project.json, src/Microsoft.Framework.ConfigurationModel/ConfigurationExtensions.cs, src/Microsoft.Framework.ConfigurationModel/Sources/EnvironmentVariablesConfigurationSource.cs, src/Microsoft.Framework.ConfigurationModel/Sources/IniFileConfigurationSource.cs, src/Microsoft.Framework.ConfigurationModel/project.json, test/Microsoft.Framework.ConfigurationModel.Json.Test/project.json, test/Microsoft.Framework.ConfigurationModel.Test.Common/project.json, test/Microsoft.Framework.ConfigurationModel.Test/project.json, test/Microsoft.Framework.ConfigurationModel.Xml.Test/XmlConfigurationSourceTest.AspNet50.cs, test/Microsoft.Framework.ConfigurationModel.Xml.Test/XmlConfigurationSourceTest.AspNetCore50.cs, test/Microsoft.Framework.ConfigurationModel.Xml.Test/project.json
Prepping to be merged once ready.
=> Update aspnet50/aspnetcore50 => dnx50/dnxcore50.

src/Microsoft.Framework.ConfigurationModel.Json/JsonConfigurationExtension.cs, src/Microsoft.Framework.ConfigurationModel.Json/JsonConfigurationSource.cs, src/Microsoft.Framework.ConfigurationModel.Json/project.json, src/Microsoft.Framework.ConfigurationModel.Xml/XmlConfigurationExtension.cs, src/Microsoft.Framework.ConfigurationModel.Xml/XmlConfigurationSource.cs, src/Microsoft.Framework.ConfigurationModel.Xml/project.json, src/Microsoft.Framework.ConfigurationModel/ConfigurationExtensions.cs, src/Microsoft.Framework.ConfigurationModel/Sources/IniFileConfigurationSource.cs, src/Microsoft.Framework.ConfigurationModel/project.json, test/Microsoft.Framework.ConfigurationModel.Json.Test/JsonConfigurationExtensionTest.cs, test/Microsoft.Framework.ConfigurationModel.Json.Test/JsonConfigurationSourceTest.cs, test/Microsoft.Framework.ConfigurationModel.Test/ConfigurationExtensionsTest.cs, test/Microsoft.Framework.ConfigurationModel.Xml.Test/XmlConfigurationExtensionTest.cs, test/Microsoft.Framework.ConfigurationModel.Xml.Test/XmlConfigurationSourceTest.cs
=> Call Resource.FormatError_FileNotFound instead of doing string.Format

src/Microsoft.Framework.Configuration.Abstractions/project.json, src/Microsoft.Framework.Configuration.Binder/project.json, src/Microsoft.Framework.Configuration.CommandLine/project.json, src/Microsoft.Framework.Configuration.EnvironmentVariables/EnvironmentVariablesConfigurationSource.cs, src/Microsoft.Framework.Configuration.EnvironmentVariables/project.json, src/Microsoft.Framework.Configuration.Ini/IniConfigurationExtension.cs, src/Microsoft.Framework.Configuration.Ini/IniFileConfigurationSource.cs, src/Microsoft.Framework.Configuration.Ini/project.json, src/Microsoft.Framework.Configuration.Json/project.json, src/Microsoft.Framework.Configuration.Xml/EncryptedXmlDocumentDecryptor.cs, src/Microsoft.Framework.Configuration.Xml/XmlDocumentDecryptor.cs, src/Microsoft.Framework.Configuration.Xml/project.json, src/Microsoft.Framework.Configuration/project.json
=> dotnet all the things

src/Microsoft.Framework.Configuration/Sources/MemoryConfigurationExtension.cs, test/Microsoft.Framework.Configuration.FunctionalTests/ConfigurationTests.cs
=> fix #193:ConfigurationExtensions.AddInMemoryCollection()

src/Microsoft.Framework.Configuration.EnvironmentVariables/EnvironmentVariables/EnvironmentVariablesConfigurationSource.cs, test/Microsoft.Framework.Configuration.EnvironmentVariables.Test/EnvironmentVariablesConfigurationSourceTest.cs
#227 
@glennc @anurse @davidfowl
=> : replaces __ in environment variables

src/Microsoft.Framework.Configuration.Binder/project.json, src/Microsoft.Framework.Configuration.CommandLine/CommandLine/CommandLineConfigurationProvider.cs, src/Microsoft.Framework.Configuration.CommandLine/project.json, src/Microsoft.Framework.Configuration.EnvironmentVariables/project.json, src/Microsoft.Framework.Configuration.Ini/IniConfigurationExtensions.cs, src/Microsoft.Framework.Configuration.Ini/project.json, src/Microsoft.Framework.Configuration.Json/JsonConfigurationExtensions.cs, src/Microsoft.Framework.Configuration.Json/project.json, src/Microsoft.Framework.Configuration.Xml/XmlConfigurationExtensions.cs, src/Microsoft.Framework.Configuration.Xml/project.json, src/Microsoft.Framework.Configuration/ConfigurationBuilder.cs, src/Microsoft.Framework.Configuration/MemoryConfigurationExtensions.cs, src/Microsoft.Framework.Configuration/Properties/Resources.Designer.cs, src/Microsoft.Framework.Configuration/Resources.resx, src/Microsoft.Framework.Configuration/project.json
I made this PR to react the changes on the commit e3f4e5d87d3abe26493b702b510d21a6fb666470
/cc @HaoK
=> React to Rename IConfigurationSource => Provider changes

src/Microsoft.Framework.Configuration.Binder/ConfigurationBinder.cs, test/Microsoft.Framework.Configuration.Binder.Test/ConfigurationBinderTests.cs
=> Add default value support to ConfigBinder.Get

README.md
Another but current blog post link about configuration namespace.
=> Configuration providers at BleedingNEdge link

.gitignore, .travis.yml, appveyor.yml, build.cmd, build.sh, src/Microsoft.Extensions.Configuration.FileExtensions/FileConfigurationExtensions.cs, src/Microsoft.Extensions.Configuration.FileProviderExtensions/ConfigurationRootExtensions.cs, test/Microsoft.Extensions.Configuration.Binder.Test/project.json, test/Microsoft.Extensions.Configuration.CommandLine.Test/project.json, test/Microsoft.Extensions.Configuration.EnvironmentVariables.Test/project.json, test/Microsoft.Extensions.Configuration.FileExtensions.Test/FileConfigurationBuilderExtensionsTest.cs, test/Microsoft.Extensions.Configuration.FileExtensions.Test/project.json, test/Microsoft.Extensions.Configuration.FileProviderExtensions.Test/project.json, test/Microsoft.Extensions.Configuration.FunctionalTests/ConfigurationTests.cs, test/Microsoft.Extensions.Configuration.FunctionalTests/project.json, test/Microsoft.Extensions.Configuration.Ini.Test/project.json, test/Microsoft.Extensions.Configuration.Json.Test/project.json, test/Microsoft.Extensions.Configuration.Test/project.json, test/Microsoft.Extensions.Configuration.Xml.Test/project.json
=> Build with dotnet

src/Microsoft.Extensions.Configuration.FileProviderExtensions/ConfigurationRootExtensions.cs, src/Microsoft.Extensions.Configuration.FileProviderExtensions/project.json, test/Microsoft.Extensions.Configuration.FileProviderExtensions.Test/ConfigurationRootExtensionsTest.cs
=> React to FileProviders namespace changes

src/Microsoft.Extensions.Configuration.Abstractions/project.json, src/Microsoft.Extensions.Configuration.Binder/project.json, src/Microsoft.Extensions.Configuration.CommandLine/project.json, src/Microsoft.Extensions.Configuration.EnvironmentVariables/project.json, src/Microsoft.Extensions.Configuration.FileExtensions/project.json, src/Microsoft.Extensions.Configuration.Ini/project.json, src/Microsoft.Extensions.Configuration.Json/project.json, src/Microsoft.Extensions.Configuration.Xml/project.json, src/Microsoft.Extensions.Configuration/project.json
=> Remove netcore50

src/Microsoft.Extensions.Configuration.Json/project.json
=> Updated Json.Net version

NuGetPackageVerifier.json, src/Microsoft.Extensions.Configuration.Abstractions/project.json, src/Microsoft.Extensions.Configuration.Binder/project.json, src/Microsoft.Extensions.Configuration.CommandLine/project.json, src/Microsoft.Extensions.Configuration.EnvironmentVariables/project.json, src/Microsoft.Extensions.Configuration.FileExtensions/project.json, src/Microsoft.Extensions.Configuration.FileProviderExtensions/project.json, src/Microsoft.Extensions.Configuration.Ini/IniConfigurationExtensions.cs, src/Microsoft.Extensions.Configuration.Ini/project.json, src/Microsoft.Extensions.Configuration.Json/JsonConfigurationExtensions.cs, src/Microsoft.Extensions.Configuration.Json/project.json, src/Microsoft.Extensions.Configuration.Xml/XmlConfigurationExtensions.cs, src/Microsoft.Extensions.Configuration.Xml/project.json, src/Microsoft.Extensions.Configuration/DefaultConfigurationBuilderExtensions.cs, src/Microsoft.Extensions.Configuration/project.json
=> Enabled xml doc generation

README.md, src/Microsoft.Extensions.Configuration.Abstractions/project.json, src/Microsoft.Extensions.Configuration.Binder/project.json, src/Microsoft.Extensions.Configuration.CommandLine/project.json, src/Microsoft.Extensions.Configuration.EnvironmentVariables/project.json, src/Microsoft.Extensions.Configuration.FileExtensions/project.json, src/Microsoft.Extensions.Configuration.FileProviderExtensions/project.json, src/Microsoft.Extensions.Configuration.Ini/project.json, src/Microsoft.Extensions.Configuration.Json/project.json, src/Microsoft.Extensions.Configuration.Xml/project.json, src/Microsoft.Extensions.Configuration/Properties/AssemblyInfo.cs, src/Microsoft.Extensions.Configuration/project.json
=> Fix package metadata

src/Microsoft.Extensions.Configuration.Abstractions/project.json, src/Microsoft.Extensions.Configuration.Binder/project.json, src/Microsoft.Extensions.Configuration.CommandLine/project.json, src/Microsoft.Extensions.Configuration.EnvironmentVariables/project.json, src/Microsoft.Extensions.Configuration.FileExtensions/project.json, src/Microsoft.Extensions.Configuration.FileProviderExtensions/project.json, src/Microsoft.Extensions.Configuration.Ini/project.json, src/Microsoft.Extensions.Configuration.Json/project.json, src/Microsoft.Extensions.Configuration.Xml/project.json, src/Microsoft.Extensions.Configuration/project.json
CR feedback from https://github.com/aspnet/Configuration/pull/397
@ajaybhargavb @HaoK @divega
=> Fix package metadata some more

src/Microsoft.Extensions.Configuration.Json/project.json
=> Updating Json.Net version

test/Microsoft.Extensions.Configuration.Binder.Test/ConfigurationBinderTests.cs, test/Microsoft.Extensions.Configuration.Binder.Test/project.json, test/Microsoft.Extensions.Configuration.CommandLine.Test/project.json, test/Microsoft.Extensions.Configuration.EnvironmentVariables.Test/project.json, test/Microsoft.Extensions.Configuration.FileExtensions.Test/FileConfigurationBuilderExtensionsTest.cs, test/Microsoft.Extensions.Configuration.FileExtensions.Test/project.json, test/Microsoft.Extensions.Configuration.FunctionalTests/ConfigurationTests.cs, test/Microsoft.Extensions.Configuration.FunctionalTests/project.json, test/Microsoft.Extensions.Configuration.Ini.Test/project.json, test/Microsoft.Extensions.Configuration.Json.Test/project.json, test/Microsoft.Extensions.Configuration.Test.Common/project.json, test/Microsoft.Extensions.Configuration.Test/project.json, test/Microsoft.Extensions.Configuration.Xml.Test/XmlConfigurationTest.AspNet50.cs, test/Microsoft.Extensions.Configuration.Xml.Test/XmlConfigurationTest.AspNetCore50.cs, test/Microsoft.Extensions.Configuration.Xml.Test/project.json
=> Migrate tests/samples/tools to portable

src/Microsoft.Extensions.Configuration.Json/project.json
@Tratcher @muratg @Eilon @davidfowl @DamianEdwards 
I'll just push all the other ones after this one, just making a PR to show the change
=> Add serialization.primitives for json

src/Microsoft.Extensions.Configuration/ConfigurationBuilder.cs, src/Microsoft.Extensions.Configuration/MemoryConfigurationBuilderExtensions.cs
Also rename Extensions class
@divega
=> Remove duplicate Load

src/Microsoft.Extensions.Configuration.FileExtensions/FileConfigurationProvider.cs, test/Microsoft.Extensions.Configuration.FunctionalTests/ConfigurationTests.cs
=> Fix reloadOnChange for delete

src/Microsoft.Extensions.Configuration.Binder/ConfigurationBinder.cs, test/Microsoft.Extensions.Configuration.Binder.Test/ConfigurationBinderTests.cs, test/Microsoft.Extensions.Configuration.Binder.Test/ConfigurationCollectionBindingTests.cs
Fixes https://github.com/aspnet/Configuration/issues/466
@divega
=> Support binding to uninitialized ICollection interfaces

src/Microsoft.Extensions.Configuration.Binder/ConfigurationBinder.cs, test/Microsoft.Extensions.Configuration.Binder.Test/ConfigurationBinderTests.cs
Fixes https://github.com/aspnet/Configuration/issues/511
@divega
=> Explicitly allow binding to object (as string)

src/Microsoft.Extensions.Configuration.AzureKeyVault/DefaultKeyVaultSecretManager.cs, test/Microsoft.Extensions.Configuration.AzureKeyVault.Test/AzureKeyVaultConfigurationTest.cs
KeyVault does not support `_` in key names.
/cc @BrennanConroy @pranavkm @glennc @cwe1ss
=> Change KeyVault section seperator from `__` to `--`

src/Microsoft.Extensions.Configuration.Abstractions/project.json, src/Microsoft.Extensions.Configuration.Binder/project.json, src/Microsoft.Extensions.Configuration.CommandLine/project.json, src/Microsoft.Extensions.Configuration.EnvironmentVariables/project.json, src/Microsoft.Extensions.Configuration.FileExtensions/project.json, src/Microsoft.Extensions.Configuration.Ini/project.json, src/Microsoft.Extensions.Configuration.Json/project.json, src/Microsoft.Extensions.Configuration.Xml/project.json, src/Microsoft.Extensions.Configuration/project.json, test/Microsoft.Extensions.Configuration.Binder.Test/project.json, test/Microsoft.Extensions.Configuration.CommandLine.Test/project.json, test/Microsoft.Extensions.Configuration.EnvironmentVariables.Test/project.json, test/Microsoft.Extensions.Configuration.FileExtensions.Test/project.json, test/Microsoft.Extensions.Configuration.FunctionalTests/project.json, test/Microsoft.Extensions.Configuration.Ini.Test/project.json, test/Microsoft.Extensions.Configuration.Json.Test/project.json, test/Microsoft.Extensions.Configuration.Test.Common/project.json, test/Microsoft.Extensions.Configuration.Test/project.json, test/Microsoft.Extensions.Configuration.Xml.Test/project.json
:arrow_up: project.json versions
cc @Eilon @pranavkm
=> Prepare rel/1.0.1 branch

samples/KeyVaultSample/EnvironmentSecretManager.cs, src/Microsoft.Extensions.Configuration.AzureKeyVault/AzureKeyVaultConfigurationExtensions.cs, src/Microsoft.Extensions.Configuration.AzureKeyVault/AzureKeyVaultConfigurationProvider.cs, src/Microsoft.Extensions.Configuration.AzureKeyVault/DefaultKeyVaultSecretManager.cs, src/Microsoft.Extensions.Configuration.AzureKeyVault/IKeyVaultClient.cs, src/Microsoft.Extensions.Configuration.AzureKeyVault/IKeyVaultSecretManager.cs, src/Microsoft.Extensions.Configuration.AzureKeyVault/KeyVaultClientWrapper.cs, src/Microsoft.Extensions.Configuration.AzureKeyVault/project.json, test/Microsoft.Extensions.Configuration.AzureKeyVault.Test/AzureKeyVaultConfigurationTest.cs
Fixes: https://github.com/aspnet/Configuration/issues/530
@anurse
=> Update Microsoft.Azure.KeyVault version

src/Microsoft.Extensions.Configuration.UserSecrets/PathHelper.cs, test/Microsoft.Extensions.Configuration.UserSecrets.Test/PathHelperTest.cs
Resolves https://github.com/aspnet/DotNetTools/issues/229
cc @divega
=> Ensure user secrets ID does not contain invalid file name characters

test/Microsoft.Extensions.Configuration.FunctionalTests/ConfigurationTests.cs
Creating PR for this to trigger the Travis Linux build and see if it works and fixes the build.
=> Fix for the broken Travis Linux build, which is logged at #468

src/Microsoft.Extensions.Configuration.AzureKeyVault/project.json
=> Update Microsoft.Azure.KeyVault package version

src/Microsoft.Extensions.Configuration.AzureKeyVault/project.json
See https://github.com/aspnet/Configuration/pull/570
=> Port "Update Microsoft.Azure.KeyVault package version" to 1.1.1

global.json, src/Microsoft.Extensions.Configuration.UserSecrets/ConfigurationExtensions.cs, src/Microsoft.Extensions.Configuration.UserSecrets/Properties/Resources.Designer.cs, src/Microsoft.Extensions.Configuration.UserSecrets/Resources.resx, test/Microsoft.Extensions.Configuration.UserSecrets.Test/ConfigurationExtensionTest.cs
Resolves #590 
NB: when merged, I will also cherry-pick this onto rel/1.1.1.
=> Obsolete .AddUserSecrets()

test/Microsoft.Extensions.Configuration.FunctionalTests/ConfigurationTests.cs
https://github.com/aspnet/Configuration/issues/645
@pranavkm
=> Disable test

test/Microsoft.Extensions.Configuration.FunctionalTests/ConfigurationTests.cs
https://github.com/aspnet/Configuration/issues/645
@pranavkm
=> Disable tests

.travis.yml, Configuration.sln, appveyor.yml, src/Microsoft.Extensions.Configuration.UserSecrets/Properties/AssemblyInfo.cs, src/Microsoft.Extensions.Configuration.UserSecrets/UserSecretsConfigurationExtensions.cs, test/Microsoft.Extensions.Configuration.UserSecrets.Test/ConfigurationExtensionTest.cs
Part of a solution for https://github.com/aspnet/MetaPackages/issues/60
=> Add overloads to AddUserSecrets with optional flag

build/dependencies.props
Related https://github.com/aspnet/BuildTools/pull/246
=> Update Microsoft.Azure.KeyVault to 2.2.1-preview

src/Microsoft.Extensions.Configuration/ConfigurationReloadToken.cs
Update ConfigurationReloadToken.cs
=> Improved documentation

build/dependencies.props, samples/KeyVaultSample/KeyVaultSample.csproj, src/Microsoft.Extensions.Configuration.AzureKeyVault/AzureKeyVaultConfigurationExtensions.cs, src/Microsoft.Extensions.Configuration.AzureKeyVault/Microsoft.Extensions.Configuration.AzureKeyVault.csproj, src/Microsoft.Extensions.Configuration.Xml/EncryptedXmlDocumentDecryptor.cs, src/Microsoft.Extensions.Configuration.Xml/Microsoft.Extensions.Configuration.Xml.csproj, src/Microsoft.Extensions.Configuration.Xml/XmlDocumentDecryptor.cs, test/Microsoft.Extensions.Configuration.AzureKeyVault.Test/Microsoft.Extensions.Configuration.AzureKeyVault.Test.csproj, test/Microsoft.Extensions.Configuration.Binder.Test/Microsoft.Extensions.Configuration.Binder.Test.csproj, test/Microsoft.Extensions.Configuration.CommandLine.Test/Microsoft.Extensions.Configuration.CommandLine.Test.csproj, test/Microsoft.Extensions.Configuration.DockerSecrets.Test/Microsoft.Extensions.Configuration.DockerSecrets.Test.csproj, test/Microsoft.Extensions.Configuration.EnvironmentVariables.Test/Microsoft.Extensions.Configuration.EnvironmentVariables.Test.csproj, test/Microsoft.Extensions.Configuration.FileExtensions.Test/Microsoft.Extensions.Configuration.FileExtensions.Test.csproj, test/Microsoft.Extensions.Configuration.FunctionalTests/Microsoft.Extensions.Configuration.FunctionalTests.csproj, test/Microsoft.Extensions.Configuration.Ini.Test/Microsoft.Extensions.Configuration.Ini.Test.csproj, test/Microsoft.Extensions.Configuration.Json.Test/Microsoft.Extensions.Configuration.Json.Test.csproj, test/Microsoft.Extensions.Configuration.Test.Common/Microsoft.Extensions.Configuration.Test.Common.csproj, test/Microsoft.Extensions.Configuration.Test/Microsoft.Extensions.Configuration.Test.csproj, test/Microsoft.Extensions.Configuration.Xml.Test/Microsoft.Extensions.Configuration.Xml.Test.csproj, test/Microsoft.Extensions.Configuration.Xml.Test/XmlConfigurationTest.cs
=> Updated projects to use net461

src/Microsoft.Extensions.Configuration.Binder/ConfigurationBinder.cs, test/Microsoft.Extensions.Configuration.Binder.Test/ConfigurationBinderTests.cs
=> Add new Bind overload

src/Microsoft.Extensions.Configuration.AzureKeyVault/AzureKeyVaultConfigurationProvider.cs
Fixes https://github.com/aspnet/Configuration/issues/664
@ajcvickers @pakrym
=> Add ConfigureAwait

src/Microsoft.Extensions.Configuration.AzureKeyVault/baseline.netcore.json, src/Microsoft.Extensions.Configuration.UserSecrets/baseline.netcore.json
Fixes https://github.com/aspnet/Configuration/issues/633
=> Add baselines for AzureKeyValue/UserSecrets

build/dependencies.props, test/Config.Binder.Test/ConfigurationCollectionBindingTests.cs, test/Config.DockerSecrets.Test/DockerSecretTests.cs, test/Config.Ini.Test/IniConfigurationExtensionsTest.cs, test/Config.Ini.Test/IniConfigurationTest.cs, test/Config.Json.Test/JsonConfigurationExtensionsTest.cs, test/Config.Json.Test/JsonConfigurationTest.cs, test/Config.Test/ConfigurationTest.cs, test/Config.Xml.Test/XmlConfigurationExtensionsTest.cs, test/Config.Xml.Test/XmlConfigurationTest.cs
Required a few small changes to code to please the new analyzers in xunit 0.6.0.
=> Upgrade to xunit 2.3.0-beta4

src/Config/ChainedConfigurationProvider.cs, src/Config/ChainedConfigurationSource.cs, src/Config/ConfigurationBuilderExtensions.cs, src/Config/ConfigurationProvider.cs, src/Config/ConfigurationRoot.cs, src/Config/ConfigurationSection.cs, test/Config.Test/ConfigurationTest.cs
Fixes https://github.com/aspnet/Configuration/issues/630
Not sure I love calling it Chained/AddConfiguration.
Maybe IncludeProvider/Source and a different verb configBuilder.Include(config)?
cc @ajcvickers @Tratcher @shirhatti
=> AddConfiguration(IConfiguration) to chain

src/Config.Binder/ConfigurationBinder.cs, test/Config.Binder.Test/ConfigurationCollectionBindingTests.cs
Copy-pasted the code from the issue, credit goes to @cwe1ss
Addresses #565
=> Modify ConfigurationBinder to use IDictionary<> setter instead of "Add" method

src/Config.Json/JsonConfigurationFileParser.cs, src/Config.Json/JsonConfigurationProvider.cs, src/Config.UserSecrets/Config.UserSecrets.csproj, src/Config.UserSecrets/build/netstandard2.0/Microsoft.Extensions.Configuration.UserSecrets.props
cref https://github.com/aspnet/Coherence-Signed/issues/668
Required for https://github.com/aspnet/DotNetTools/pull/355
=> Set the LocalUserSecrets project capability when UserSecrets is referenced

build/dependencies.props, src/Config.AzureKeyVault/AzureKeyVaultConfigurationExtensions.cs, src/Config.AzureKeyVault/AzureKeyVaultConfigurationProvider.cs, src/Config.AzureKeyVault/Config.AzureKeyVault.csproj, test/Config.AzureKeyVault.Test/AzureKeyVaultConfigurationTest.cs
https://github.com/aspnet/Configuration/issues/766
=> Add KeyVault overloads with MSI support

build/dependencies.props
https://github.com/aspnet/Universe/issues/1108
=> Update MicrosoftAzureServicesAppAuthenticationPackageVersion to stable

src/Config.KeyPerFile/KeyPerFileConfigurationBuilderExtensions.cs, test/Config.KeyPerFile.Test/KeyPerFileTests.cs
Fixes https://github.com/aspnet/Configuration/issues/818
@ajcvickers @shirhatti @glennc
=> Fix KeyPerFile bug with optional = true

test/Config.KeyPerFile.Test/KeyPerFileTests.cs
Backfort from master of fix for https://github.com/aspnet/Configuration/issues/871
@natemcmaster
=> Update expected error message due to changes in file provider

src/Config.Ini/IniConfigurationProvider.cs, src/Config.Ini/IniConfigurationSource.cs
=> HTTP --> HTTPS

README.md
Reacting to https://github.com/aspnet/Extensions/pull/463.
This repo will be archived as active development of these API has moved into aspnet/Extensions. Updating the README to point to the new repo.
=> This repo is merging into aspnet/Extensions and will be archived
